Algoritmo "Imprimindo uma mensagem, seguida do conteúdo de uma variável"
// Data atual: 15/05/2025

// Algoritmo para imprimir uma mensagem, seguida do conteúdo atribuído á uma
// Variável do tipo caractere (string).

Var
// Seção de Declarações das variáveis 
   Jogo: Caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Jogo <- "The Witcher"
   Escreval ("Jogo: ", Jogo)
Fimalgoritmo