Algoritmo "Imprimindo uma mensagem, seguida do conteúdo da variável."
// Data atual: 15/05/2025

// Algoritmo para imprimir uma mensagem, seguida do conteúdo atribuído á uma
// Variável do tipo caractere (string).

Var
// Seção de Declarações das variáveis 
   Msg: Caractere
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Msg <- "Olá, Mundo!"
   Escreval ("Mensagem: ", Msg)
Fimalgoritmo