Algoritmo "05"
// Data atual: 31/05/2025

// 05) Escreva um algoritmo para ler um valor (do teclado) e escrever (na tela)
// o seu antecessor.

Var
   // Seção de Declarações das variáveis
   Valor, Antecessor: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva ("Informe um valor: ")
   Leia (Valor)

   Antecessor <- Valor - 1

   Escreval ()
   Escreval ("O antecessor de ", Valor, " é ", Antecessor, ".")
Fimalgoritmo