Algoritmo "Arrays - Vetores"
// Data atual: 05/07/2025

// Algoritmo para preenchimento de um vetor e exibição de seus valores.

Var
   // Seção de Declarações das variáveis
   i: Inteiro
   Vet: Vetor [0..5] de Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   // Preencher Vetor
   Para i de 0 ate 5 faca
      Escreva ("Informe o ", i+1, "o. valor: ")
      Leia (Vet[i])
   FimPara
   Escreval ()

   // Exibir Valores do Vetor
   Para i de 0 ate 5 faca
      Escreval (Vet[i])
   FimPara
Fimalgoritmo