Algoritmo "032"
// Data atual: 30/05/2025

// 32) Faça um algoritmo que receba o peso de uma pessoa em quilos, calcule e
// mostre esse peso em gramas.

Var
   // Seção de Declarações das variáveis
   Peso, Gramas: Real

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva ("Informe seu peso (Kg): ")
   Leia (Peso)

   Gramas <- (Peso * 1000)

   Escreval ()
   Escreval ("Seu peso em gramas corresponde a: ", Gramas, " gramas.")
Fimalgoritmo