Algoritmo "037"
// Data atual: 30/05/2025

// 36) Faça um algoritmo que calcule e mostre a tabuada de um número digitado
// pelo usuário.

Var
   // Seção de Declarações das variáveis
   Valor, i: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva ("Informe um valor: ")
   Leia (Valor)
   Escreval ()

   Para i de 1 ate 10 faca
      Escreval (Valor, " X ", i, " = ", Valor * i)
   FimPara
Fimalgoritmo