Algoritmo "Funções Aritméticas - Cálculo de Seno"
// Data atual: 15/05/2025

// Algoritmo para converter um determinado valor, de graus para radianos,
// Calcular o seno desse valor convertido e imprimir o resultado na tela.

Var
// Seção de Declarações das variáveis 
   S: Real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   S <- Sen(GrauPRad(90))
   Escreval ("O seno de 90 graus é:", S)
Fimalgoritmo