Algoritmo "Função Aritmética - Cálculo do Coseno"
// Data atual: 15/05/2025

// Algoritmo para converter um determinado valor, de graus para radianos,
// Calcular o cosseno desse valor convertido e imprimir o resultado na tela.

Var
// Seção de Declarações das variáveis 
   C: Real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   C <- Cos(GrauPRad(30))
   Escreval ("O cosseno de 30 graus é:", C)
Fimalgoritmo