Algoritmo "Função Aritmética - Cálculo da Tangente"
// Data atual: 15/05/2025

// Algoritmo para converter um determinado valor, de graus para radianos,
// Calcular a tangente desse valor convertido e imprimir o resultado na tela.

Var
// Seção de Declarações das variáveis 
   T: Real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   T <- Tan(GrauPRad(30))
   Escreval ("A tangente de 30 graus é:", T)
Fimalgoritmo