Algoritmo "Cálculo da área de um círculo"
// Data atual: 22/05/2025

// Algoritmo para calcular a área de um círculo.

Var
// Seção de Declarações das variáveis 
   Raio, Area: Real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva ("Informe uma medida para o raio: ")
   Leia (Raio)
   
   Area  <- Pi * (Raio ^ 2)
   
   Escreval()
   Escreval ("A área do círculo é de ", Area:5:1)
Fimalgoritmo