Algoritmo "080"
// Data atual: 05/06/2025

// Escreva um programa que efetue a leitura de um determinado valor, e o
// apresente na tela somente se o número fornecido pelo usuário for maior
// que 3.

Var
   // Seção de Declarações das variáveis
   Valor: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva ("Informe um valor: ")
   Leia (Valor)
   Escreval ()

   Se (Valor > 3) entao
      Escreval ("Valor: ", Valor)
   FimSe
Fimalgoritmo