Algoritmo "093"
// Data atual: 08/06/2025

// Programa para ler um valor e informar se ele é ou não é múltiplo de 3.

Var
   // Seção de Declarações das variáveis
   Valor: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva ("Informe um valor: ")
   Leia (Valor)
   Escreval ()

   Se (Valor % 3 = 0) entao
      Escreval (Valor, " é múltiplo de 3.")
   Senao
      Escreval (Valor, " não é múltiplo de 3.")
   FimSe
Fimalgoritmo