Algoritmo "132"
// Data atual: 12/06/2025

// Escreva um programa que realize uma contagem de 1 á 10 utilizando estrutura
// de repetição "Enquanto" (While).

Var
   // Seção de Declarações das variáveis
   Cont: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Cont <- 1
   Enquanto (Cont <= 10) faca
      Escreva (Cont)
      Cont <- Cont + 1
   FimEnquanto
Fimalgoritmo