Algoritmo "133"
// Data atual: 12/06/2025

// Escreva um programa que realize uma contagem progressiva de 0 á 100 de 10 em
// 10 utilizando estrutura de repetição "Enquanto" (While).

Var
   // Seção de Declarações das variáveis
   Cont: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Cont <- 0
   Enquanto (Cont <= 100) faca
      Escreva (Cont)
      Cont <- Cont + 10
   FimEnquanto
Fimalgoritmo