Algoritmo "134"
// Data atual: 12/06/2025

// Escreva um programa que realize uma contagem regressiva de 10 á 1 utilizando
// Estrutura de repetição "Enquanto" (While).

Var
   // Seção de Declarações das variáveis
   Cont: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Cont <- 10
   Enquanto (Cont >= 1) faca
      Escreva (Cont)
      Cont <- Cont - 1
   FimEnquanto
Fimalgoritmo