Algoritmo "135"
// Data atual: 12/06/2025

// Escreva um programa que realize uma contagem regressiva de 100 á 0 de 10 em
// 10 utilizando estrutura de repetição "Enquanto" (While).

Var
   // Seção de Declarações das variáveis
   Cont: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Cont <- 100
   Enquanto (Cont >= 0) faca
      Escreva (Cont)
      Cont <- Cont - 10
   FimEnquanto
Fimalgoritmo