Algoritmo "183"
// Data atual: 19/06/2025

// Algoritmo para fazer uma contagem progressiva de 1 ate 10 utilizando
// Estrutura de repetição "Para" (For).

Var
   // Seção de Declarações das variáveis
   i: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Para i de 1 ate 10 faca
      Escreva (i)
   FimPara
   Escreval ()
   Escreval ("Fim da Contagem!")
Fimalgoritmo