Algoritmo "184"
// Data atual: 19/06/2025

// Algoritmo para fazer uma contagem progressiva de 0 a 30 (de 5 em 5)
// Utilizando estrutura de repetição "Para" (For).

Var
   // Seção de Declarações das variáveis
   i: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Para i de 0 ate 30 passo 5 faca
      Escreva (i)
   FimPara
   Escreval ()
   Escreval ("Fim da Contagem!")
Fimalgoritmo