Algoritmo "185"
// Data atual: 19/06/2025

// Algoritmo para fazer uma contagem regressiva de 10 a 1 utilizando estrutura
// De repetição "Para" (For).

Var
   // Seção de Declarações das variáveis
   i: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Para i de 10 ate 1 passo -1 faca
      Escreva (i)
   FimPara
   Escreval ()
   Escreval ("Fim da Contagem!")
Fimalgoritmo