Algoritmo "186"
// Data atual: 19/06/2025

// Algoritmo para fazer uma contagem regressiva de 30 a 0 (de 5 em 5) utilizando
// Estrutura de repetição "Para" (For).

Var
   // Seção de Declarações das variáveis
   i: Inteiro
   
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Para i de 30 ate 0 passo -5 faca
      Escreva (i)
   FimPara
   Escreval ()
   Escreval ("Fim da Contagem!")
Fimalgoritmo