Algoritmo "187"
// Data atual: 19/06/2025

// Algoritmo para realizar a soma dos 100 primeiros números inteiros utilizando
// Estrutura de repetição "Para" (For).

Var
   // Seção de Declarações das variáveis
   i, Soma: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Soma <- 0
   Para i de 1 ate 100 faca
      Soma <- Soma + i
   FimPara
   Escreval ()
   Escreval ("Soma dos Valores (1 a 100): ", Soma)
Fimalgoritmo