Algoritmo "190"
// Data atual: 19/06/2025

// Algoritmo para exibir a tabuada de qualquer valor que o usuário digitar
// Utilizando estrutura de repetição "Para" (For).

Var
   // Seção de Declarações das variáveis
   i, Valor: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva ("Tabuada: ")
   Leia (Valor)
   Escreval ()

   Para i de 1 ate 10 faca
      Escreval (Valor, " x ", i, " = ", Valor * i)
   FimPara
Fimalgoritmo