Algoritmo "192"
// Data atual: 19/06/2025

// Algoritmo para ler 10 valores digitados pelo usuário e soma-los utilizando
// Estrutura de repetição "Para" (For).

Var
   // Seção de Declarações das variáveis
   i, Valor, Soma: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Soma <- 0
   Para i de 1 ate 10 faca
      Escreva ("Informe o ", i, "o. valor: ")
      Leia (Valor)

      Escreval ("--------------------------")

      Soma <- Soma + Valor
   FimPara
   Escreval ()
   Escreval ("Soma dos Valores: ", Soma)
Fimalgoritmo