Algoritmo "193"
// Data atual: 19/06/2025

// Algoritmo para realizar uma contagem de 1 a 50 e exibir somente os números
// ímpares dessa contagem, utilizando estrutura de repetição "Para" (For).

Var
   // Seção de Declarações das variáveis
   i: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Para i de 1 ate 50 faca
      Se (i % 2 <> 0) entao
         Escreva (i)
      FimSe
   FimPara
Fimalgoritmo