Algoritmo "196"
// Data atual: 19/06/2025

// Algoritmo para realizar uma contagem regressiva de 50 a 1 e exibir somente
// os números pares dessa contagem, utilizando estrutura de repetição "Para"
// (For).

Var
   // Seção de Declarações das variáveis
   i: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Para i de 50 ate 1 passo -1 faca
      Se (i % 2 = 0) entao
         Escreva (i)
      FimSe
   FimPara
Fimalgoritmo