Algoritmo "221"
// Data atual: 21/06/2025

// Algoritmo de combinações numéricas utilizando aninhamento de estruturas de
// Repetição "Para" (For).

Var
   // Seção de Declarações das variáveis
   i, j: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Para i de 0 ate 3 faca
      Para j de 0 ate 3 faca
         Escreva ("(", i,",", j,")")
      FimPara
      Escreval ()
   FimPara
Fimalgoritmo