Algoritmo "222"
// Data atual: 21/06/2025

// Escreva um programa que calcule e exiba a tabuada de 1 á 10. Utilize
// Aninhamento de estruturas de repetição.

Var
   // Seção de Declarações das variáveis
   i, j: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Para i de 1 ate 10 faca

      Para j de 1 ate 10 faca
         Escreval (i, " x ", j, " = ", i * j)
      FimPara
      Escreval ()
      
   FimPara
Fimalgoritmo