Algoritmo "223"
// Data atual: 21/06/2025

// Escreva um algoritmo que receba 5 números e imprima a metade de cada um na
// tela.

Var
   // Seção de Declarações das variáveis
   i, Valor: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Para i de 1 ate 5 faca
      Escreva ("Informe o ", i, "o. valor: ")
      Leia (Valor)
      Escreval ("Metade do ", i, "o. valor: ", Valor/2)
      Escreval ("------------------------------------")
   FimPara
Fimalgoritmo