Algoritmo "224"
// Data atual: 21/06/2025

// Algoritmo para exibir um conjunto de números iguais que se repetem de acordo
// com o valor do número, utilizando aninhamento de estruturas de repetição.

Var
   // Seção de Declarações das variáveis
   i, j, Valor: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva ("Informe um valor: ")
   Leia (Valor)
   Escreval ()

   Para i de 1 ate Valor faca

      Para j de 1 ate i faca
         Escreva (i)
      FimPara
      Escreval ()

   FimPara
Fimalgoritmo