Algoritmo "230"
// Data atual: 21/06/2025

// Escreva um algoritmo que calcule a soma geral dos valores até um valor
// determinado pelo usuário.

Var
   // Seção de Declarações das variáveis
   i, Valor, Soma_Total: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva ("informe um valor: ")
   Leia (Valor)
   Escreval ()

   Soma_Total <- 0
   
   Para i de 1 ate Valor faca
      Soma_Total <- Soma_Total + i
   FimPara
   Escreval ("Soma Total dos Valores Até ", Valor, ": ", Soma_Total)
Fimalgoritmo