Algoritmo "241"
// Data atual: 23/06/2025

// Escreva um algoritmo que gere uma string aleatória, utilize a função
// "Aleatorio" do Visualg, essa função gera strings de forma aleatória.

Var
   // Seção de Declarações das variáveis
   Texto: Caractere

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva ("Gerando String de Texto Aleatória: ")
   Aleatorio On
   Leia (Texto)
   Aleatorio Off
Fimalgoritmo