Algoritmo "242"
// Data atual: 23/06/2025

// Escreva um algoritmo que gere vários números de uma vez, dentro de um
// intervalo, de forma aleatória, utilize a função "Aleatorio" do Visualg,
// essa função gera valores de forma aleatória dentro de um intervalo
// específico.

Var
   // Seção de Declarações das variáveis
   i, Valores_Comp: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Aleatorio On
   Para i de 1 ate 100 faca
      Leia (Valores_Comp)
   FimPara
   Aleatorio Off
Fimalgoritmo