Algoritmo "243"
// Data atual: 25/06/2025

// Procedimento para exibir a string "Hello, World!".

Var
   // Seção de Declarações das variáveis

Procedimento String ()
Inicio
   Escreval ("+--------------------------+")
   Escreval ("        HELLO, WORLD!       ")
   Escreval ("+--------------------------+")
FimProcedimento

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   String ()
Fimalgoritmo