Algoritmo "244"
// Data atual: 25/06/2025

// Procedimento para exibir uma mensagem digitada pelo usuário. (Passagem de
// Parâmetro por valor).

Var
   // Seção de Declarações das variáveis
   Resposta: Caractere

Procedimento String (Texto: Caractere)
Inicio
   Escreval ("+------------------------+")
   Escreval (            Texto           )
   Escreval ("+------------------------+")
FimProcedimento

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva ("Mensagem: ")
   Leia (Resposta)
   Escreval ()

   String (Resposta)
Fimalgoritmo