Algoritmo "250"
// Data atual: 25/06/2025

// Procedimento para somar dois valores. (Passagem de parâmetro por referência).

Var
   // Seção de Declarações das variáveis
   X, Y: Inteiro

Procedimento Soma (Var A, B: Inteiro)
Inicio
   Escreval ("A soma entre ", A, " e ", B, " é ", A + B)
FimProcedimento

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval ("Informe dois valores inteiros: ")
   Leia (X, Y)
   Escreval ()

   Soma (X, Y)
Fimalgoritmo