Algoritmo "254"
// Data atual: 25/06/2025

// Procedimento para somar 10 valores informados pelo usuário.

Var
   // Seção de Declarações das variáveis

Procedimento Soma ()
Var
   i, Valor, S: Inteiro
Inicio
   S <- 0
   Para i de 1 ate 10 faca
      Escreva ("Informe o ", i, "o. valor: ")
      Leia (Valor)

      S <- S + Valor
   FimPara
   Escreval ()
   Escreval ("Soma dos Valores: ", S)
Fimprocedimento

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Soma ()
Fimalgoritmo