Algoritmo "255"
// Data atual: 25/06/2025

// Procedimento para contagem de 1 a 100 exibindo somente os valoers pares.

Var
   // Seção de Declarações das variáveis

Procedimento Pares ()
Var
   i: Inteiro
Inicio
   Para i de 1 ate 100 faca
      Se (i % 2 = 0) entao
         Escreva (i)
      FimSe
   Fimpara
FimProcedimento

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Pares ()
Fimalgoritmo