Algoritmo "256"
// Data atual: 25/06/2025

// Procedimento para contagem de 1 a 100 exibindo somente os valoers impares.

Var
   // Seção de Declarações das variáveis

Procedimento Impares ()
Var
   i: Inteiro
Inicio
   Para i de 1 ate 100 faca
      Se (i % 2 <> 0) entao
         Escreva (i)
      FimSe
   FimPara
FimProcedimento

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Impares ()
Fimalgoritmo