Algoritmo "261"
// Data atual: 25/06/2025

// Procedimento para calcular e exibir as tabuadas de 1 a 10.

Var
   // Seção de Declarações das variáveis

Procedimento Tabuadas ()
Var
   i, j: Inteiro
Inicio
   Para i de 1 ate 10 faca
      Para j de 1 ate 10 faca
         Escreval (i, " x ", j, " = ", i * j)
      FimPara
      Escreval ()
   FimPara
FimProcedimento

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Tabuadas ()
Fimalgoritmo