Algoritmo "267"
// Data atual: 26/06/2025

// Procedimento para somar os quadrados de 2 a 5.

Var
   // Seção de Declarações das variáveis

Procedimento Soma_Potencia ()
Var
   i: Inteiro
   Soma: Real
Inicio
   Para i de 2 ate 5 faca
      Soma <- Soma + Exp(i, 2)
   FimPara
   Escreval ("Soma dos quadrados de 2 a 5: ", Soma)
FimProcedimento

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Soma_Potencia ()
Fimalgoritmo