Algoritmo "274"
// Data atual: 30/06/2025

// Função para somar dois valores informados pelo usuário.

Var
   // Seção de Declarações das variáveis
   V1, V2, S: Inteiro

Funcao Soma (N1, N2: Inteiro): Inteiro
   Retorne (N1 + N2)
Inicio
FimFuncao

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva ("Informe um valor: ")
   Leia (V1)
   Escreva ("Informe outro valor: ")
   Leia (V2)
   Escreval ()

   S <- Soma (V1, V2)

   Escreval ("Soma entre ", V1, " e ", V2, ": ", S)
Fimalgoritmo