Algoritmo "285"
// Data atual: 08/07/2025

// Crie um vetor de 8 índices e atribua o valor 999 a todos os índices.
// Índice = Posição do vetor.

Var
   // Seção de Declarações das variáveis
   i: Inteiro
   Vet: Vetor [0..7] de Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Para i de 0 ate 7 faca
      Vet[i] <- 999
      Escreva (Vet[i])
   FimPara
Fimalgoritmo