Algoritmo "286"
// Data atual: 08/07/2025

// Crie um vetor de 10 índices que armazena o resultado dos índices do vetor
// Multiplicado por 5.

Var
   // Seção de Declarações das variáveis
   i: Inteiro
   Vet: Vetor [0..9] de Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Para i de 0 ate 9 faca
      Vet[i] <- (i+1) * 5
      Escreva (Vet[i])
   FimPara
Fimalgoritmo