Algoritmo "288"
// Data atual: 08/07/2025

// Crie um vetor de 10 índices, preencha-o e exiba os valores do vetor.

Var
   // Seção de Declarações das variáveis
   i: Inteiro
   Vet: Vetor [0..9] de Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   // Preencher o Array
   Para i de 0 ate 9 faca
      Escreva ("Informe o ", i + 1, "o. valor: ")
      Leia (Vet[i])
   FimPara
   Escreval ()
   
   // Exibir os Valores do Array
   Para i de 0 ate 9 faca
      Escreva (Vet[i])
   FimPara
   Escreval ()
Fimalgoritmo