Algoritmo "291"
// Data atual: 08/07/2025

// Crie um vetor de 10 índices, atribua o valor do índice ao vetor e exiba os
// Valores em ordem decrescente.

Var
   // Seção de Declarações das variáveis
   i: Inteiro
   Vet: Vetor [0..9] de Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Para i de 9 ate 0 passo -1 faca
      Vet[i] <- i
      Escreva (Vet[i])
   FimPara
   Escreval ()
Fimalgoritmo