Algoritmo "Rotinas - Procedimentos"
// Data atual: 25/06/2025

// Procedimento para somar dois valores.

Var
   // Seção de Declarações das variáveis
   X, Y: Inteiro

Procedimento Soma (A, B: Inteiro)
Inicio
   Escreval ("Recebi o valor: ", A)
   Escreval ("Recebi o valor: ", B)
   Escreval ("A soma entre os valores é: ", A + B)
FimProcedimento

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   X <- 5
   Y <- 3
   Soma (X, Y)
Fimalgoritmo