Algoritmo "Estruturas Condicionais"
// Data atual: 04/06/2025

// Algoritmo para ler um valor e informar se ele é PAR ou ÍMPAR.

Var
   // Seção de Declarações das variáveis
   Valor: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva ("Informe um valor: ")
   Leia (Valor)
   Escreval ()
   
   Se (Valor % 2 = 0) então
      Escreval (Valor, " é PAR.")
   Senao
      Escreval (Valor, " é ÍMPAR.")
   FimSe
Fimalgoritmo