Algoritmo "Comando de Saída"
// Data atual: 24/05/2025

// 2) Faça um programa que leia o nome de uma pessoa e mostre uma mensagem de
// Boasvindas para ela. Ex:
// Qual é o seu nome? João da Silva
// Olá João da Silva, é um prazer te conhecer!

Var
// Seção de Declarações das variáveis 
   Nome: Caractere
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva ("Qual é seu nome? ")
   Leia (Nome)
   Escreval ("Olá, ", Nome, "! Muito prazer!")
Fimalgoritmo