Algoritmo "01 - Estruturas de Repetição - Enquanto (While)"
// Data atual: 10/06/2025

// Algoritmo para contar de 1 a 10 utilizando a estrutura de repetição
// Enquanto (While).

Var
   // Seção de Declarações das variáveis
   Cont: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Cont <- 1
   Enquanto (Cont <= 10) faca
      Escreva (Cont)
      Cont <- Cont + 1
   FimEnquanto
Fimalgoritmo