Algoritmo "02 - Estruturas de Repetição - Enquanto (While)"
// Data atual: 10/06/2025

// Algoritmo para contar de 5 em 5 até 50 utilizando estrutura de repetição
// enquanto (While).

Var
   // Seção de Declarações das variáveis
   Cont: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Cont <- 0
   Enquanto (Cont <= 50) faca
      Escreva (Cont)
      Cont <- Cont + 5
   FimEnquanto
Fimalgoritmo