Algoritmo "03 - Estruturas de Repetição Enquanto (While)"
// Data atual: 10/06/2025

// Algoritmo para contar de forma regressiva de 10 até 1 utilizando estrutura
// de repetição Enquanto (While).

Var
   // Seção de Declarações das variáveis
   Cont: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Cont <- 10
   Enquanto (Cont >= 1) faca
      Escreva (Cont)
      Cont <- Cont - 1
   FimEnquanto
Fimalgoritmo