Algoritmo "04 - Estruturas de Repetição - Enquanto (While)"
// Data atual: 10/06/2025

// Algoritmo para contar de forma regressiva de 5 em 5 utilizando estrutura
// de repetição Enquanto (While).

Var
   // Seção de Declarações das variáveis
   Cont: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Cont <- 50
   Enquanto (Cont >= 1) faca
      Escreva (Cont)
      Cont <- Cont - 5
   FimEnquanto
Fimalgoritmo