Algoritmo "Estrutura de Repetição Repita - Do-While"
// Data atual: 16/06/2025

// Algoritmo para contar de de 1 á 100 (de 10 em 10) utilizando estrutura de
// Repetição "Repita" (Do-While).

Var
   // Seção de Declarações das variáveis
   i: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   i <- 0
   Repita
      Escreva (i)
      i <- i + 10
   Ate (i > 100)
Fimalgoritmo