Algoritmo "Estrutura de Repetição Repita - Do-While"
// Data atual: 16/06/2025

// Algoritmo para contagem regressiva de 10 á 1 utilizando estrutura de repetição
// "Repita" (Do-While).

Var
   // Seção de Declarações das variáveis
   i: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   i <- 10
   Repita
      Escreva (i)
      i <- i - 1
   Ate (i < 1)
Fimalgoritmo