Algoritmo "Estrutura de Repetição Repita - Do-While"
// Data atual  : 16/06/2025

// Algoritmo para fazer uma contagem regressiva de 100 á 0 (de 10 em 10)
// Utilizando estrutura de repetição "Repita" (Do-While).

Var
   // Seção de Declarações das variáveis
   i: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   i <- 100
   Repita
      Escreva (i)
      i <- i - 10
   Ate (i < 0)
Fimalgoritmo