Algoritmo "Estrutura de Repetição Para - For"
// Data atual: 18/06/2025

// Algoritmo para somar dez valores informados pelo usuário utilizando a
// Estrutura de repetição "Para" (For).

Var
   // Seção de Declarações das variáveis
   i, Soma, Valor: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Soma <- 0
   Para i de 1 ate 10 faca
      Escreva ("Informe o " , i , "o. valor: ")
      Leia (Valor)
      
      Soma <- Soma + Valor
   FimPara
   Escreval ()
   Escreval ("Soma dos Valores: ", Soma)
Fimalgoritmo