Algoritmo "Estrutura de Repetição Para - For"
// Data atual: 18/06/2025

// Algoritmo para contar de forma progressiva até um valor limite determinado
// pelo usuário, exibindo somente os valores pares, utilizando estrutura de
// repetição "Para" (For).

Var
   // Seção de Declarações das variáveis
   i, Valor_Limite: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva ("Informe um valor limite para a contagem: ")
   Leia (Valor_Limite)
   Escreval ()

   Para i de 0 ate Valor_Limite passo 2 faca
      Escreva (i)
   FimPara
Fimalgoritmo