Algoritmo "Estrutura de Repetição Para - For"
// Data atual: 18/06/2025

// Algoritmo de combinações numéricas utilizando aninhamento de estruturas de
// Repetição "Para" (For).

Var
   // Seção de Declarações das variáveis
   i, j: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Para i de 1 ate 3 faca
      Para j de 1 ate 3 faca
         Escreval (i, j)
      FimPara
   FimPara
Fimalgoritmo