Algoritmo "020"
// Data atual: 09/06/2025

// 20) Desenvolva um programa que leia um número inteiro e mostre se ele é PAR
// ou ÍMPAR.

Var
   // Seção de Declarações das variáveis
   Valor: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva ("Informe um valor: ")
   Leia (Valor)
   Escreval ()

   Se (Valor % 2 = 0) entao
      Escreval (Valor, " é PAR.")
   Senao
      Escreval (Valor, " é IMPAR.")
   FimSe
Fimalgoritmo