Algoritmo "038"
// Data atual: 10/06/2025

// 38) Escreva um programa que mostre na tela a seguinte contagem:
// 6 7 8 9 10 11 Acabou!

Var
   // Seção de Declarações das variáveis
   Cont: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Cont <- 6
   Enquanto (Cont <= 11) faca
      Escreval (Cont)
      Cont <- Cont + 1
   FimEnquanto
   Escreval ()
   Escreval ("Fim da Contagem!")
Fimalgoritmo