Algoritmo "039"
// Data atual: 10/06/2025

// 39) Faça um algoritmo que mostre na tela a seguinte contagem:
// 10 9 8 7 6 5 4 3 Acabou!

Var
   // Seção de Declarações das variáveis
   Cont: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Cont <- 10
   Enquanto (Cont >= 3) faca
      Escreval (Cont)
      Cont <- Cont - 1
   FimEnquanto
   Escreval ()
   Escreval ("Fim da Contagem!")
Fimalgoritmo