Algoritmo "040"
// Data atual: 10/06/2025

// 40) Crie um aplicativo que mostre na tela a seguinte contagem:
// 0 3 6 9 12 15 18 Acabou!

Var
   // Seção de Declarações das variáveis
   Cont: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Cont <- 0
   Enquanto (Cont <= 18) faca
      Escreval (Cont)
      Cont <- Cont + 3
   FimEnquanto
   Escreval ()
   Escreval ("Fim da Contagem!")
Fimalgoritmo