Algoritmo "041"
// Data atual: 10/06/2025

// 41) Desenvolva um programa que mostre na tela a seguinte contagem:
// 100 95 90 85 80 ... 0 Acabou!

Var
   // Seção de Declarações das variáveis
   Cont: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Cont <- 100
   Enquanto (Cont >= 0) faca
      Escreva (Cont)
      Cont <- Cont - 5
   FimEnquanto
   Escreval ()
   Escreval ("Fim da Contagem!")
Fimalgoritmo