Algoritmo "061"
// Data atual: 17/06/2025

// 61) Crie um programa que mostre na tela a seguinte contagem, usando a
// estrutura "Repita" (Do-While):
// 0 3 6 9 12 15 18 21 24 27 30 Acabou!

Var
   // Seção de Declarações das variáveis
   i: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   i <- 0
   Repita
      Escreva (i)
      i <- i + 3
   Ate (i > 30)
   Escreval ()
   Escreval ("Fim da Contagem!")
Fimalgoritmo