Algoritmo "064"
// Data atual: 19/06/2025

// 64) Desenvolva um programa usando a estrutura “para” que mostre na tela a
// seguinte contagem:
// 0 5 10 15 20 25 30 35 40 Acabou!

Var
   // Seção de Declarações das variáveis
   i: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Para i de 0 ate 40 passo 5 faca
      Escreva (i)
   FimPara
   Escreval ()
   Escreval ("Fim da Contagem!")
Fimalgoritmo