Algoritmo "065"
// Data atual: 19/06/2025

// 65) Desenvolva um programa usando a estrutura “para” que mostre na tela a
// seguinte contagem:
// 100 90 80 70 60 50 40 30 20 10 0 Acabou!

Var
   // Seção de Declarações das variáveis
   i: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Para i de 100 ate 0 passo -10 faca
      Escreva (i)
   FimPara
   Escreval ()
   Escreval ("Fim da Contagem!")
Fimalgoritmo