Algoritmo "066"
// Data atual: 19/06/2025

// 66) Escreva um programa que leia um número qualquer e mostre a tabuada desse
// número, usando a estrutura “para”.

Var
   // Seção de Declarações das variáveis
   i, Valor: Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva ("Informe um valor: ")
   Leia (Valor)
   Escreval ()
   
   Para i de 1 ate 10 faca
      Escreval (Valor, " x ", i, " = ", Valor * i)
   FimPara
Fimalgoritmo