Algoritmo "067"
// Data atual: 19/06/2025

// 67) Faça um programa usando a estrutura “para” que leia um número inteiro
// positivo e mostre na tela uma contagem de 0 até o valor digitado:
// Ex: Digite um valor: 9
// Contagem: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, FIM!

Var
   // Seção de Declarações das variáveis
   i, Valor_Limite: Inteiro
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva ("Informe um valor limite para a contagem: ")
   Leia (Valor_Limite)
   Escreval ()

   Para i de 0 até Valor_Limite faca
      Escreva (i)
   FimPara
   Escreval ()
   Escreval ("Fim da Contagem!")
Fimalgoritmo