Algoritmo "071"
// Data atual: 08/07/2025

// 71) Faça um programa que preencha automaticamente um vetor numérico com 8
// posições, conforme abaixo: 999 999 999 999 999 999 999 999

Var
   // Seção de Declarações das variáveis
   i: Inteiro
   Vet: Vetor [0..7] de Inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Para i de 0 ate 7 faca
      Vet[i] <- 999
      Escreva (Vet[i])
   FimPara
Fimalgoritmo