Algoritmo "086"
// Data atual: 26/06/2025

// 86) Crie um programa que tenha um procedimento Gerador() que, quando chamado,
// mostre a mensagem "Olá, Mundo!" com algum componente visual (linhas)
// Ex: Ao chamar Gerador() aparece:
// +-------=======------+
//       Olá, Mundo!
// +-------=======------+

Var
// Seção de Declarações das variáveis 

Procedimento Gerador ()
Inicio
   Escreval ("+---------------------+")
   Escreval ("      Olá, Mundo!      ")
   Escreval ("+---------------------+")
FimProcedimento

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Gerador ()
Fimalgoritmo